name: Main workflow

on: [push]

env:
  CACHE_IMAGE: jchavarri/ocaml_webapp
  DOCKER_BUILDKIT: 0

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Log in to docker hub
        run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}
      - name: Build base from dockerfile
        run: |
          docker build \
            --target base \
            --tag $CACHE_IMAGE:base \
            --file ./Dockerfile \
            "."
      - name: Build client from dockerfile
        run: |
          docker build \
            --target client \
            --tag $CACHE_IMAGE:client \
            --file ./Dockerfile \
            "."
      - name: Build stage from dockerfile
        run: |
          docker build \
            --tag $CACHE_IMAGE:stage \
            --file ./Dockerfile \
            "."
      - name: Push base image to docker hub
        run: docker push $CACHE_IMAGE:base
      - name: Push client image to docker hub
        run: docker push $CACHE_IMAGE:client
      - name: Push stage image to docker hub
        run: docker push $CACHE_IMAGE:stage
